const defaultSettings = require('./settings.json')

const NODE_ENV = process.env.NODE_ENV || defaultSettings.NODE_ENV
const NODE_CONFIG_SET = process.env.NODE_CONFIG_SET || defaultSettings.NODE_CONFIG_SET
const NODE_API_PUBLIC = process.env.NODE_API_PUBLIC || defaultSettings.NODE_API_PUBLIC
const NODE_API_INTERNAL = process.env.NODE_API_INTERNAL || defaultSettings.NODE_API_INTERNAL
const NODE_PATHS_BASE = process.env.NODE_PATHS_BASE || defaultSettings.NODE_PATHS_BASE
const NODE_SERVER_PORT = process.env.NODE_SERVER_PORT || defaultSettings.NODE_SERVER_PORT
const NODE_SERVER_PREFIX = process.env.NODE_SERVER_PREFIX || defaultSettings.NODE_SERVER_PREFIX
const NODE_SETTINGS_GOOGLE_ANALYTICS_ID = process.env.NODE_SETTINGS_GOOGLE_ANALYTICS_ID || defaultSettings.NODE_SETTINGS_GOOGLE_ANALYTICS_ID
const NODE_SETTINGS_LANGUAGE_COOKIE_NAME = process.env.NODE_SETTINGS_LANGUAGE_COOKIE_NAME || defaultSettings.NODE_SETTINGS_LANGUAGE_COOKIE_NAME
const NODE_SETTINGS_LANGUAGE_HEADER_NAME = process.env.NODE_SETTINGS_LANGUAGE_HEADER_NAME || defaultSettings.NODE_SETTINGS_LANGUAGE_HEADER_NAME

module.exports = {
  NODE_API_INTERNAL,
  NODE_API_PUBLIC,
  NODE_CONFIG_SET,
  NODE_ENV,
  NODE_PATHS_BASE,
  NODE_SERVER_PORT,
  NODE_SERVER_PREFIX,
  NODE_SETTINGS_GOOGLE_ANALYTICS_ID,
  NODE_SETTINGS_LANGUAGE_COOKIE_NAME,
  NODE_SETTINGS_LANGUAGE_HEADER_NAME
}
